export const Characters = [
  {
    name: "Zulrak",
    healthPoints: 67,
    strength: 49,
    dexterity: 32,
    power: 39,
    knowledge: 78,
    appearance: 91,
    education: 81,
    size: 51,
    intelect: 65,
    movement: 0,
    avatar: "../../assets/img/zulrak.jpg",
    currentHealth: 43,
  },
  {
    name: "Iskander",
    healthPoints: 16,
    strength: 85,
    dexterity: 55,
    power: 50,
    knowledge: 75,
    appearance: 25,
    education: 75,
    size: 85,
    intelect: 50,
    movement: 0,
    avatar: "../../assets/img/kundox.jpg",
    currentHealth: 10,
  },
  {
    name: "Kennedian",
    healthPoints: 43,
    strength: 54,
    dexterity: 67,
    power: 52,
    knowledge: 51,
    appearance: 76,
    education: 61,
    size: 39,
    intelect: 65,
    movement: 0,
    avatar: "../../assets/img/outlander.jpg",
    currentHealth: 37,
  },
  {
    name: "Fanrisa",
    healthPoints: 56,
    strength: 34,
    dexterity: 56,
    power: 43,
    knowledge: 82,
    appearance: 95,
    education: 79,
    size: 35,
    intelect: 91,
    movement: 0,
    avatar: "../../assets/img/mage.jpg",
    currentHealth: 25,
  },
  {
    name: "Hawkrager",
    healthPoints: 56,
    dexterity: 86,
    strength: 76,
    power: 62,
    knowledge: 43,
    appearance: 34,
    education: 32,
    size: 73,
    intelect: 75,
    movement: 0,
    avatar: "../../assets/img/berserker.jpg",
    currentHealth: 12,
  },
];
